pageinfo = [[1216688353,5213],
	[1216687867,4814],
	[1216857841,15819],
	[1216865131,4377],
	[1246941501,4586],
	[1247102519,41286],
	[1216958581,30975],
	[1216691661,3606],
	[1216876087,12147],
	[1247102491,7109],
	[1247102499,13551],
	[1216870005,11939],
	[1234324625,2240],
	[1216863785,3684],
	[1216958587,8453],
	[1216958583,11037],
	[1216958581,6529],
	[1216863787,10738],
	[1216958575,4435],
	[1216856637,4385],
	[1216692913,4311],
	[1216865263,2135],
	[1216863855,7782],
	[1216875913,1949],
	[1216688485,5447],
	[1216875593,11716],
	[1218515809,5150],
	[1216861757,10235],
	[1216958159,12564],
	[1247005785,11832],
	[1216865235,2978],
	[1216875809,5292],
	[1234326233,16541],
	[1216865295,2735],
	[1216687915,2644],
	[1216875789,4795],
	[1224044477,20913],
	[1217394373,12074],
	[1216865231,5071],
	[1216862645,7815],
	[1216692315,4296],
	[1216863791,7708],
	[1216875721,2307],
	[1216958009,12227],
	[1221537089,11572],
	[1216865223,2047],
	[1216687905,2040]];
pagedata = [ ["./2d_graphics_tests.htm","2D Graphics Test","﻿2D Graphics Test Top Previous Next This suite contains a number of tests that exercise Qt&#39;s QPainter graphics functions and the video card. The n...",""],
["./3d_graphics_test.htm","3D Graphics Test","﻿3D Graphics Test Top Previous Next Tests the OpenGL&#39;s graphics system. This test creates and animates an OpenGL depth buffer with RGBA or color i...",""],
["./cd_rom_and_dvd_test.htm","CD ROM and DVD Test","﻿CD ROM and DVD Test Top Previous Next Tests the CD-ROM and DVD and optionally the sound card (when used with a music CD). This test can be used w...",""],
["./cd_rom_dvd_preferences.htm","CD-ROM/DVD Preferences","﻿CD-ROM/DVD Preferences Top Previous Next CD-ROM/DVD test preferences CD/DVD Selection and test method These fields allow the user to select the C...",""],
["./command_line_parameters.htm","Command Line Parameters","﻿Command Line Parameters Top Previous Next -C configname BurnInTest will load the config file specified. -D duration Sets the test duration to the...",""],
["./command_line_version.htm","Command Line Version","﻿Command Line Version Top Previous Next The command line version of BurnInTest does not have a Graphical User Interface and as such does not requi...",""],
["./common_error_messages.htm","Common Error Messages","﻿Common Error Messages Top Previous Next When BurnInTest encounters an error during a test run a short description of the error is displayed in th...",""],
["./contacting_passmark_software.htm","Contacting PassMark Software","﻿Contacting PassMark Software Top Previous Next On the Web You can contact PassMark on the web at: http://www.passmark.com E-Mail For technical su...",""],
["./detailed_error_log_history.htm","Detailed Error log history","﻿Detailed Error log history Top Previous Next The detailed error log history can be opened from the ‘View / Error log file’ menu. It contains a re...",""],
["./disk_preferences.htm","Disk Preferences","﻿Disk Preferences Top Previous Next Disk test preferences Partitioned drives they must be mounted before BurnInTest can test them, they also need ...",""],
["./disk_test.htm","Hard Disk and Floppy Disk Test","﻿Hard Disk and Floppy Disk Test Top Previous Next This suite contains a number of tests that exercise the mass storage units (Hard disk or otherwi...",""],
["./duty_cycles.htm","Test Selection and Duty Cycles","﻿Test Selection and Duty Cycles Top Previous Next From this window it is possible to configure the automatic stopping of tests, select the tests t...",""],
["./entering_a_licence_key.htm","Entering A Licence Key","﻿Entering A Licence Key Top Previous Next Licence keys for BurnInTest Linux will be in the form; -----START_OF_KEY----- TestUser #BIA3AGSBFARC4AR9...",""],
["./error_handling_preferences.htm","Error Handling Preferences","﻿Error Handling Preferences Top Previous Next Action on Error When BurnInTest detects an error, three options are available. 1. Continue. The erro...",""],
["./example_ascii_log_file.htm","Example ASCII Log file","﻿Example ASCII Log file Top Previous Next ASCII (Text) log files can be created using the logging option in the Test preferences dialog. The ASCII...",""],
["./fault_finding.htm","Fault finding","﻿Fault finding Top Previous Next What follows are some hints on how go about finding the cause of particular system instability. We don’t want to ...",""],
["./interpreting_the_results.htm","Interpreting the results","﻿Interpreting the results Top Previous Next Status display In the main window there is a display that shows a summary of all the results of all th...",""],
["./logging_preferences.htm","Logging Preferences","﻿Logging Preferences Top Previous Next Logging to the Detailed Error log history Errors are automatically logged to the Detailed Error log history...",""],
["./loopback_plugs.htm","Making Loopback plugs","﻿Making Loopback plugs Top Previous Next You can purchase high quality molded loop back plugs from PassMark or, for the serial and parallel versio...",""],
["./machine_identity.htm","Machine Identity and Additional Notes","﻿Machine Identity and Additional Notes Top Previous Next The fields on this screen allow the entry of information related to the identity of the m...",""],
["./maintaining_multiple_test_configurations.htm","Maintaining Multiple Test Configurations","﻿Maintaining Multiple Test Configurations Top Previous Next If you are in the business to testing many different computers then you may benefit fr...",""],
["./maths_preferences.htm","CPU Math Preferences","﻿CPU Math Preferences Top Previous Next Using the check boxes it is possible to select which maths tests will be performed and which ones will be ...",""],
["./maths_tests.htm","CPU Maths Test","﻿CPU Maths Test Top Previous Next This test contains two sub categories, integer and floating point, which contain 8 different tests in total. For...",""],
["./memory_preferences.htm","Memory Preferences","﻿Memory Preferences Top Previous Next One of the test patterns can be selected for the test or the default option Cyclic can be used, which will c...",""],
["./memory_test.htm","Memory (RAM) test","﻿Memory (RAM) test Top Previous Next Tests the Memory in the computer. The Memory test, tests the reliability of the RAM installed in the computer...",""],
["./menu_options.htm","Menu Options","﻿Menu Options Top Previous Next File Save test log Save the current log to a location as specified by user. Print Allows the contents of the main ...",""],
["./network_preferences.htm","Network Preferences","﻿Network Preferences Top Previous Next Network addresses Up to 6 network addresses can be entered for the simultaneous testing of the connection t...",""],
["./network_test.htm","Network Test","﻿Network Test Top Previous Next The Network test tests your networking hardware and software. This is done by sending special ICMP_ECHO message us...",""],
["./overview.htm","Introduction and Overview","﻿Introduction and Overview Top Next BurnInTest is a software tool that allows all the major sub-systems of a computer to be simultaneously tested ...",""],
["./parallel_port_loop_back_plug.htm","Parallel port loop back plug","﻿Parallel Port Loopback plug Top Previous The parallel port on IBM compatible PCs have always used a DB-25 connector. However, over time several c...",""],
["./parallel_port_preferences.htm","Parallel Port Preferences","﻿Parallel Port Preferences Top Previous Next Parallel port The communications port that will be used by the parallel port test, eg /dev/lp0, /dev/...",""],
["./parallel_test.htm","Parallel Port Test","﻿Parallel Port Test Top Previous Next Tests the parallel communications port connected to the PC. The parallel port to be tested can be selected f...",""],
["./precautions_for_thorough_and_careful_testing.htm","Precautions for thorough and careful testing","﻿Precautions for thorough and careful testing Top Previous Next For a hardware test to be useful several precautions need to be taken. Failure to ...",""],
["./pre_test_preferences.htm","Pre-test Preferences","﻿Pre-test Preferences Top Previous Next Action before running tests You may specify the default behaviour of BurnInTest before it begins any test ...",""],
["./purchase.htm","How to Purchase BurnInTest","﻿How to Purchase BurnInTest Top Previous Next Price US Dollars: $49 (single user) See the PassMark website http://www.passmark.com/sales Please no...",""],
["./quick_start.htm","Quick Start Guide","﻿Quick Start - How to Start Testing Top Previous Next Here’s a summary of the steps to go through to start testing; 1. Use the Test Duty Cycles wi...",""],
["./scripting.htm","Scripting","﻿Scripting Top Previous Next BurnInTest includes a simple scripting language that allows tests to be executed in a sequence. A PASS/FAIL indicatio...",""],
["./serial_port_loopback_plug.htm","Serial port loopback plug","﻿Serial Port Loopback Plug Top Previous Next The serial port on IBM compatible PCs conform to the RS232 electrical standard and use a male DB-9 co...",""],
["./serial_port_preferences.htm","Serial Port Preferences","﻿Serial Port Preferences Top Previous Next Adding a serial port To select a serial port for testing, select the COM port number (ttyS0-63) from th...",""],
["./serial_test.htm","Serial Port Test","﻿Serial Port Test Top Previous Next Tests the serial communications ports connected to the PC. Up to 64 serial ports may be tested simultaneously....",""],
["./system_requirements.htm","System Requirements","﻿System Requirements Top Previous Next Hardware requirements: - Intel and AMD compatible CPU. - Recommended 256MB of memory. - 2MB Disk space (mor...",""],
["./test_descriptions.htm","Test Descriptions","﻿Test Descriptions Top Previous Next Several tests are built into the software. Each of these tests contains one or more sub-tests designed to exe...",""],
["./test_window_display.htm","Test Window display","﻿Test Window display Top Previous Next Each test type has its own display window. The contents of the windows are described in the various tests. ...",""],
["./usb_loopback_plugs.htm","USB Loopback Plugs","﻿USB Loopback Plugs Top Previous Next USB 2 Loopback plugs can be used to help diagnose, troubleshoot and load test your PC’s USB 1.x and 2.0 port...",""],
["./usb_test.htm","USB Test","﻿USB Test Top Previous Next Tests the USB (Universal Serial Bus) communications ports connected to the PC. The number of USB devices to test can b...",""],
["./usb_test_preferences.htm","USB Test Preferences","﻿USB Test Preferences Top Previous Next Maximum number of USB ports This is the maximum number of USB plugs BurnInTest will attempt to connect to....",""],
["./whats_new.htm","What&#39;s New","﻿What&#39;s New Top Previous Next Please see our version history online at http://www.passmark.com/products/bitlinux_history.htm ",""]];
